[tool.poetry]
name = "prefixmaps"
version = "0.1.4"
description = "A python library for retrieving semantic prefix maps"
readme = "README.md"
authors = ["cmungall <cjm@berkeleybop.org>"]
keywords = ["semantic web", "bioinformatics"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[tool.poetry.urls]
repository = "https://github.com/linkml/prefixmaps"
homepage = "https://github.com/linkml/prefixmaps"
"Bug Tracker" = "https://github.com/linkml/prefixmaps/issues"


[tool.poetry.dependencies]
python = "^3.7.6"
pyyaml = ">=5.3.1"
importlib-metadata = "^4.12.0"
sphinx-rtd-theme = {version = "^1.0.0", extras = ["docs"]}
Sphinx = {version = "^5.3.0", extras = ["docs"]}
sphinx-autodoc-typehints = {version = "^1.19.4", extras = ["docs"]}
sphinx-click = {version = "^4.3.0", extras = ["docs"]}
myst-parser = {version = "^0.18.1", extras = ["docs"]}
click = "^8.1.3"
requests = {version = "^2.28.1", extras = ["refresh"]}
# Anticipate bioregistry ^0.6.0 will require adaptation
bioregistry = {version = "<0.6.0", extras = ["refresh"]}
rdflib = {version = "^6.2.0", extras = ["refresh"]}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
linkml = "^1.3.1"
curies = "^0.3.0"
coverage = "^6.4.4"

[tool.poetry.extras]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-autodoc-typehints",
    "sphinx-click",
    "myst-parser"
]
refresh = [
    "requests",
    "bioregistry",
    "rdflib"
]

[tool.black]
line-length = 100
target-version = ["py39", "py310"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
slurp-prefixmaps = "prefixmaps.ingest.etl_runner:cli"

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
reverse_relative = true
